# ワークフローの名前
name: Deploy to Firebase Hosting

# ワークフローが起動するきっかけ
on:
  push:
    branches:
      - main # mainブランチにpushされたら起動

# 実行する一連の作業
jobs:
  deploy:
    runs-on: ubuntu-latest # Ubuntu環境で実行
    steps:
      # 1. リポジトリのコードをチェックアウト（コピー）してくる
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Firebase Hostingへのデプロイを実行する
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SIDEPOCKETSL }}' # ステップ2で設定した合言葉を使う
          channelId: live
          projectId: side-pocket-sl # あなたのプロジェクトID
